spring: 
  datasource: 
    username: dbuser
    password: '{cipher}AQA5JaWsUNIhjdVLolaoVAy+1DxDK6+d6qdUQocRGGJNY4fbgKZlZ1cHfj3S5jFpPX1kL13OGA0QUsckGp2d/yUbEGe8dANmsfBTI/QAadafuPtZiG1lCMsnkJT+obiCPctxaeCf1cZaVfs5x8eRxbQ4yez9r2auhf2ag7gR7KgVPPe7Y8THhxBaeQuk5PtgoiyGE2LpPb3SHHxf+SPVDJoGgyMRoiYeoClMgToMWRxpDfTzJ7kkJgU3hoHN9waKK8+IfU/Tyoxm4R15pOQs+Fa7hk9MUCs7qXlXhPgGBT0EPEcBOYvtNV2M0JkjAPPmYmEdvhFVNslFMpr5SHGFbxBtmfPqoz7fCW4F2pNIrIhz7v6GVhqTT4EtwYfnsZEOjH8='