spring: 
  datasource: 
    username: dbuser
    password: '{cipher}AQAW2kKYiqQrQOdwrg6Q3MQH3b0uXtaSxRefnqmTFzOKJ3f1Kvn23FP31IGT5pDArGC74pQcwJRVDNd/UtBednX6RzdY9lFZs+H6R3a3ZaBsvKXuO+AzdlrK7UEo/dvFnrQV31+WlN2Kzhqa3uftDv+vE49b49hSA3oQg9YceuC5sqmGIdrRDpLfRPa+YQ9yEAtPHkw1Uxldk/UNiWEBTuGfJIRV0JpCweAsc7izxcDLrjcQ3SNwenul1n5U6Rs4I1+Dbr00qT6OLQENrqwkkdCW8u+EAbF48m1drpneCka1vFzO+b9d7wHZTVxwWt9npDn9I2JHoN4irPfRtlfmeqocghycefJqEReATByEjEi/vv+7n0cwkCPv7ZQyX+2w0Ko='